logging.level:
  org.springframework: DEBUG

server:
  error:
    includeStacktrace: ALWAYS

yada.contextPath: /gw

spring.cloud.gateway.routes:
  - uri: http://localhost:3012
    predicates:
      - Svc=${yada.contextPath}/svc,msp
    filters:
      - ApiAuth
      - RewritePath=${yada.contextPath}/svc(?<segment>/?.*),$\{segment}
  - uri: http://localhost:3001
    predicates:
      - Svc=${yada.contextPath}/svc,user
    filters:
      - ApiAuth=noCheckPower
      - RewritePath=${yada.contextPath}/svc(?<segment>/?.*),$\{segment}
  - uri: http://localhost:8080
    predicates:
      - Path=${yada.contextPath}/**
    filters:
      - RewritePath=${yada.contextPath}(?<segment>/?.*),$\{segment}

management.endpoints:
  web.exposure.include: metrics,gateway
  health.show-details: always

yada.security:
  defaultPwd: 111111
  pwdStrength: 1
  recaptcha:
    type: None
    secret: 6Leu2NsUAAAAAKbXdSjLz6_c1cf8qX2bL4xfn1mN
    sitekey: 6Leu2NsUAAAAAFttLaiyEKDu9yLgrYJhN77Ou1ge
    proxyHost:
    proxyPort: 8080
  token:
    secret: yadajwt
    expire: 3600

yada.db.mongo.uri: 'mongodb://localhost/msp_auth?replicaSet=rs'

spring:
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false